 logging:
   level:
     com.netflix: WARN
     org.springframework.web: WARN
     com.optimagrowth: DEBUG
---
spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: organization-service
          uri: lb://organization-service2
          predicates:
            - Path=/organization/**
          filters:
            - RewritePath=/organization/(?<path>.*), /$\{path}