spring:
  cloud:
    # function:
    #   definition: orgChange;
    stream:
      bindings:
        orgChange-out-0:
          destination: orgChangeTopic
          content-type: application/json
      kafka:
        binder:
          auto-create-topics: true
          brokers: 192.168.0.119
