services:
  database:
    image: postgres:14
    restart: on-failure
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "ostock_dev"
    volumes:
        - ./init.sql:/docker-entrypoint-initdb.d/1-init.sql
        - ./data.sql:/docker-entrypoint-initdb.d/2-data.sql
        - ./keycloak.sql:/docker-entrypoint-initdb.d/3-keycloak.sql
    networks:
      backend:
        aliases:
          - "database"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
  configserver:
    image: ostock/configserver:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
       - "8071:8071"
    environment:
      ENCRYPT_KEY: "fje83Ki8403Iod87dne7Yjsl3THueh48jfuO9j4U2hf64Lo"
    networks:
      backend:
        aliases:
          - "configserver"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8071/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  eurekaserver:
    image: ostock/eurekaserver:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - "8070:8070"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    depends_on:
      #database:
      #  condition: service_healthy
      configserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "eurekaserver"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8070/actuator/health"]
      interval: 10s
      timeout: 5s
      retries: 5
  gatewayserver:
    image: ostock/gatewayserver:0.0.1-SNAPSHOT
    restart: on-failure
    ports:
      - "8072:8072"
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
    depends_on:
      # database:
      #   condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    networks:
      backend:
        aliases:
          - "gateway"
  licensingservice:
    image: ostock/licensing-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8180:8180"
    networks:
      - backend
  organizationservice:
    image: ostock/organization-service:0.0.1-SNAPSHOT
    restart: on-failure
    environment:
      SPRING_PROFILES_ACTIVE: "dev"
      ENCRYPT_KEY:       "IMSYMMETRIC"
    depends_on:
      database:
        condition: service_healthy
      configserver:
        condition: service_healthy
      eurekaserver:
        condition: service_healthy
    ports:
      - "8081:8081"
    networks:
      - backend

  keycloak:
    image: quay.io/keycloak/keycloak:18.0
    restart: on-failure
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_DB: postgres
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: keycloak
      KC_DB_URL: jdbc:postgresql://database:5432/keycloak
    command:
      - "start-dev"
    depends_on:
      database:
        condition: service_healthy
    ports:
      - "8080:8080"
    networks:
      backend:
        aliases:
          - "keycloak"

networks:
  backend:
    driver: bridge
